#!/usr/bin/env python
import requests
from pynag.Plugins import PluginHelper, ok, critical


helper = PluginHelper()

helper.parser.add_option(
    '-H', dest="host", help="hostname of elasticsearch to check",
    default="localhost")
helper.parser.add_option(
    '-P', dest="protocol", help="protocol to use (default http)",
    default='http')
helper.parser.add_option(
    '-p', dest="port", help="port number to use (default 80)", default='80')

helper.parse_arguments()

url = "%s://%s:%s/" %\
    (helper.options.protocol, helper.options.host, helper.options.port)

try:
    data = requests.get(url).json()

    if data['status'] == 200:
        helper.status(ok)
        helper.add_summary("%s" % data['status'])
    else:
        helper.status(critical)
        helper.add_summary("status of %s is %s" % (url, data['status']))
except Exception as e:
    helper.status(critical)
    helper.add_summary(
        'Could not connect to elasticsearch host "%s": %s' % (url, str(e)))

helper.check_all_metrics()
helper.exit()
