#! /bin/bash
#
# Usage: ./check_radtest username password hostname radiuspassword
#

# Paths to commands used in this script.  These
# may have to be modified to match your system setup.
# TV: removed PATH restriction. Need to think more about what this means overall
#PATH=""

ECHO="/bin/echo"
GREP="/bin/egrep"
DIFF="/usr/bin/diff"
TAIL="/usr/bin/tail"
CAT="/bin/cat"
RM="/bin/rm"
CHMOD="/bin/chmod"
TOUCH="/bin/touch"
RADTEST="/usr/bin/radtest"

PROGNAME=`/usr/bin/basename $0`
PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
REVISION="1.0.0"

. $PROGPATH/utils.sh

print_usage() {
    echo "Usage: $PROGNAME username password hostname radiuspassword"
    echo "Usage: $PROGNAME --help"
    echo "Usage: $PROGNAME --version"
}

print_help() {
    print_revision $PROGNAME $REVISION
    echo ""
    print_usage
    echo ""
    echo "radtest wrapper for nagios"
    echo ""
    support
}

# Make sure the correct number of command line
# arguments have been supplied

if [ $# -lt 1 ]; then
    print_usage
    exit $STATE_UNKNOWN
fi

exitstatus=$STATE_WARNING #default
while test -n "$1"; do
    case "$1" in
        --help)
            print_help
            exit $STATE_OK
            ;;
        --version)
            print_revision $PROGNAME $REVISION
            exit $STATE_OK
            ;;
        -V)
            print_revision $PROGNAME $REVISION
            exit $STATE_OK
            ;;
        -h)
            hostname=$2
            shift
            ;;
        -u)
            username=$2
            shift
            ;;
        -p)
            password=$2
            shift
            ;;
        -s)
            secret=$2
            shift
            ;;
        *)
            echo "Unknown argument: $1"
            print_usage
            exit $STATE_UNKNOWN
            ;;
    esac
    shift
done

$RADTEST $username $password $hostname 1 $secret &> /dev/null

ret_val=$?

if [ "$ret_val" = "0" ]; then
    $ECHO "Radius check ok - $username passed\n"
    exitstatus=$STATE_OK
else # Print total matche count and the last entry we found
    $ECHO "Radius check failed - $username unable to authenticate\n"
    exitstatus=$STATE_CRITICAL
fi

exit $exitstatus
